### ISSUE TITLE
yolov3.weight 파일 오류

### ISSUE THREAD

**Issue by KIMJEONGMIN1008** [geunbum/TeamZZang#4]
yolov3.weight이 용량이 커서 문제가 있음. clone할 때 weights파일은 clone이 안되거나 push할 때 weights파일이 안 올라가지는 문제 발생

**Comment by geunbum** [comment]
!!중요!!
github 홈페이지에서 visual studi code로 가져올 때 yolov3.weights 파일 없으니깐 참고,
코드 같은거 수정하고 로컬로 push할 때 weights 파일은 뺴고 올려야함
-> 용량 부족으로 계속 문제 발생되서 빼고 올리는걸로 조치함 대신 weights파일 다운로드 URL주소 업로드!!
